<?php

use Illuminate\Database\Seeder;

use Illuminate\Database\Eloquent\Model;
 
use Faker\Factory as Faker;

class HospitalTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('hospitals')->truncate();

         DB::table('hospitals')->insert([
            [
                'name'                 => 'Badda General Hospital and Diagnostic Centre Ltd',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '1', 
                'address'              => '1072 North Badda ( Pragati Sarani ) , dhakah 1212',
                'ownership'            => 'Private',
                'activities'           => '2004',
                'beds'                 =>'30',
                'doctors'              =>'20',
                'phone'             => '9857828',
                ],
                [
                'name'                 => 'Shaheed Suhrawardy Medical College',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '2',    
                'address'              => 'Sher - e - Bengali Nagar , dhakah 1207',
                'ownership'            => 'Government',
                'activities'           => '2004',
                'beds'                 =>'30',
                'doctors'              =>'20',
                'phone'             => '8144048',
                ],
                [
                'name'                 => 'Asian Cardiac and General Hospital',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '1',    
                'address'              => '313 barih , blakah - B , Mohammadpur , dhakah 1207',
                'ownership'            => 'Private',
                'activities'           => '2002',
                'beds'                 =>'26',
                'doctors'              =>'20',
                'phone'             => '98578455',
                ],
                [
                'name'                 => 'Birdem Hospital',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '1',    
                'address'              => '122 , Kazi Nazrul Islam Avenue , sahbaga dhakah 1000',
                'ownership'            => 'Private',
                'activities'           => '2004',
                'beds'                 =>'30',
                'doctors'              =>'20',
                'phone'             => '98572243',
                ],
                [
                'name'                 => 'Al- Safi Hospital',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '1',    
                'address'              => 'barih -9 , -6 Road , mirapurah -10 / A , PSD pallabi , dhakah 1216',
                'ownership'            => 'Private',
                'activities'           => '2004',
                'beds'                 =>'50',
                'doctors'              =>'40',
                'phone'             => '9857444',
                ],
                [
                'name'                 => 'Shahabuddin Medical College Hospital.',
                'division_id' => '1',
                'district_id' => '3',
                'category_id' => '1',    
                'address'              => 'Barih 15/15, Road -113 / A, gulasanah II, dhakah 1212 ',
                'ownership'            => 'Private',
                'activities'           => '2003',
                'beds'                 =>'80',
                'doctors'              =>'20',
                'phone'             => '986557556',
                ],
                [
                'name'                 => 'Latifa Poly Clinic Diagnostic Center.',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '2',    
                'address'              => 'Barih 30, blakah D, mirapurah -1, next to Sony Cinema Hall, 1216 dhakah',
                'ownership'            => 'Private',
                'activities'           => '1986',
                'beds'                 =>'300',
                'doctors'              =>'150',
                'phone'             => '98544357556',
                ],
                [
                'name'                 => 'Urban Health Center II (randhunu Clinic)',
                'division_id' => '1',
                'district_id' => '2',
                'category_id' => '2',    
                'address'              => 'Barih 7, rodah II / A, blakah-J',
                'ownership'            => 'Local funding',
                'activities'           => '1992',
                'beds'                 =>'100',
                'doctors'              =>'50',
                'phone'             => '986679556',
                ],
                [
                'name'                 => 'Mary-stop clinic.',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '2',    
                'address'              =>'Rupnagar Branch, Mirpur ',
                'ownership'            => 'Foreign financing',
                'activities'           => '2008',
                'beds'                 =>'150',
                'doctors'              =>'60',
                'phone'             => '967457556',
                ],
                [
                'name'                 => 'Rajshahi Burn Clinic and Diagnostic Center',
                'division_id' => '2',
                'district_id' => '14',
                'category_id' => '2',    
                'address'              => 'Lokkhipur ',
                'ownership'            => 'Private',
                'activities'           => '2003',
                'beds'                 =>'150',
                'doctors'              =>'60',
                'phone'             => '075197756',
                ],
                [
                'name'                 => 'Hoisneara Clinic',
                'division_id' => '2',
                'district_id' => '14',
                'category_id' => '2',    
                'address'              => 'Lokkhipur',
                'ownership'            => 'Local funding',
                'activities'           => '2001',
                'beds'                 =>'80',
                'doctors'              =>'20',
                'phone'             => '986457556',
                ],
                [
                'name'                 => 'New Health Care Clinic and Diagnostic Center.',
                'division_id' => '2',
                'district_id' => '14',
                'category_id' => '2',    
                'address'              => 'CMB mor ',
                'ownership'            => 'Private',
                'activities'           => '2006',
                'beds'                 =>'100',
                'doctors'              =>'40',
                'phone'             => '986450005',
                ],
                [
                'name'                 => 'Ideal Dental Clinic.',
                'division_id' => '3',
                'district_id' => '22',
                'category_id' => '2',    
                'address'              => ' Chah -49, Maina Bagh Road',
                'ownership'            => 'Private',
                'activities'           => '2002',
                'beds'                 =>'120',
                'doctors'              =>'40',
                'phone'             => '986787556',
                ],

                [
                'name'                 => 'Eye Bell optics Clinic.',
                'division_id' => '3',
                'district_id' => '22',
                'category_id' => '2',    
                'address'              => ' Gobindapur market',
                'ownership'            => 'Private',
                'activities'           => '2003',
                'beds'                 =>'80',
                'doctors'              =>'20',
                'phone'             => '986457906',
                ],

                [
                'name'                 => 'Akhi Nahar Eye Hospital.',
                'division_id' => '4',
                'district_id' => '33',
                'category_id' => '2',    
                'address'              => '3/4 Taj Mahal Road,khulna ',
                'ownership'            => 'Private',
                'activities'           => '2003',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],
                [
                'name'                 => 'Al-Arafat Hospital .',
                'division_id' => '4',
                'district_id' => '34',
                'category_id' => '2',    
                'address'              => '39 Mitford Road,Bagerhat ',
                'ownership'            => 'Private',
                'activities'           => '2006',
                'beds'                 =>'100',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],

                [
                'name'                 => 'Sylhet City Clinic .',
                'division_id' => '5',
                'district_id' => '23',
                'category_id' => '2',    
                'address'              => '3 / A, 33/34, janasana Road, bazaar Road ',
                'ownership'            => 'Private',
                'activities'           => '2008',
                'beds'                 =>'190',
                'doctors'              =>'80',
                'phone'             => '986489556',
                ],

                [
                'name'                 => 'Advanced Digital Diagnostic Center.',
                'division_id' => '5',
                'district_id' => '29',
                'category_id' => '2',    
                'address'              => '3/19, Humayun Road, Block 13',
                'ownership'            => 'Private',
                'activities'           => '2001',
                'beds'                 =>'100',
                'doctors'              =>'40',
                'phone'             => '98889556',
                ],

                [
                'name'                 => 'Islamia Eye Care Hospital.',
                'division_id' => '6',
                'district_id' => '47',
                'category_id' => '2',    
                'address'              => '3/4 Taj Mahal Road,Barishal ',
                'ownership'            => 'Private',
                'activities'           => '2003',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],
                [
                'name'                 =>'Green View Clinic.',
                'division_id' => '6',
                'district_id' => '46',
                'category_id' => '2',    
                'address'              => ' 253, Green Road',
                'ownership'            => 'Private',
                'activities'           => '2003',
                'beds'                 =>'100',
                'doctors'              =>'40',
                'phone'             => '9867899556',
                ],

                [
                'name'                 => 'Al-Safi Hospital.',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '3',    
                'address'              => 'Barih -9, -6 Road, mirapurah -10 / A, PSD pallabi, dhakah 1216',
                'ownership'            => 'Private',
                'activities'           => '2001',
                'beds'                 =>'80',
                'doctors'              =>'30',
                'phone'             => '986489678',
                ],

                [
                'name'                 => 'Victoria Health Care Ltd.',
                'division_id' => '1',
                'district_id' => '3',
                'category_id' => '3',    
                'address'              => ' Cosmopolitan Center (second floor), 222, Bab0r Road',
                'ownership'            => 'Private',
                'activities'           => '2003',
                'beds'                 =>'70',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],

                [
                'name'                 => 'Lab Aid Medical Center .',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '3',    
                'address'              => ' Barih 13 / A, Road -35, 1212 gulasanah',
                'ownership'            => 'Private',
                'activities'           => '2005',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],
                [
                'name'                 => 'Elite Clinic and Diagnostic Complex',
                'division_id' => '2',
                'district_id' => '14',
                'category_id' => '3',    
                'address'              => '16/14, Babar Road, blakah-B, ',
                'ownership'            => 'Private',
                'activities'           => '2001',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],  
                
                [
                'name'                 => 'Popular Diagnostic & Hospital Limited.',
                'division_id' => '3',
                'district_id' => '22',
                'category_id' => '3',    
                'address'              => '3/4 Taj Mahal Road ',
                'ownership'            => 'Private',
                'activities'           => '2001',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '9864649556',
                ],  
                
                [
                'name'                 => 'New poppy General Hospital and Diagnostic .',
                'division_id' => '3',
                'district_id' => '22',
                'category_id' => '3',    
                'address'              => '3/4 Taj Mahal Road ',
                'ownership'            => 'Private',
                'activities'           => '2003',
                'beds'                 =>'100',
                'doctors'              =>'38',
                'phone'             => '986489556',
                ],  
                
                [
                'name'                 => 'Pacific Dental Care.',
                'division_id' => '4',
                'district_id' => '33',
                'category_id' => '3',    
                'address'              => '3/4 Taj Mahal Road ',
                'ownership'            => 'Private',
                'activities'           => '2003',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],  
                [
                'name'                 => 'IC Hospital Limited.',
                'division_id' => '5',
                'district_id' => '43',
                'category_id' => '3',    
                'address'              => '3/4 Taj Mahal Road ',
                'ownership'            => 'Private',
                'activities'           => '2005',
                'beds'                 =>'150',
                'doctors'              =>'60',
                'phone'             => '986489556',
                ],  
                
                [
                'name'                 => 'Population kantala and debholyapamenta Organization.',
                'division_id' => '6',
                'district_id' => '47',
                'category_id' => '3',    
                'address'              => '6/4 Taj Mahal Road ',
                'ownership'            => 'Private',
                'activities'           => '2007',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],
                [
                'name'                 => 'Sobuj Bengala Diagnostic Centre .',
                'division_id' => '2',
                'district_id' => '15',
                'category_id' => '3',    
                'address'              => '3/4 Taj Mahal Road ',
                'ownership'            => 'Private',
                'activities'           => '2003',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],
                [
                'name'                 => 'Badda General Hospital and Diagnostic Centre Pvt Ltd.',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '4',    
                'address'              => '1072 North Badda (Pragati Sarani), dhakah 1212',
                'ownership'            => 'Private',
                'activities'           => '2008',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ], 

                [
                'name'                 => 'Victoria Health Care Ltd.',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '4',    
                'address'              => 'Cosmopolitan Center (second floor), 222, Babar Road, Mohammadpur, Dhaka 1207 ',
                'ownership'            => 'Private',
                'activities'           => '2006',
                'beds'                 =>'100',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],  


                [
                'name'                 => 'Hoisneara Clinic.',
                'division_id' => '1',
                'district_id' => '2',
                'category_id' => '4',    
                'address'              => '8/9 Taj Mahal Road ',
                'ownership'            => 'Private',
                'activities'           => '2003',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],  


                [
                'name'                 => 'Premier Diagnostic Centre Limited.',
                'division_id' => '1',
                'district_id' => '3',
                'category_id' => '4',    
                'address'              => '40/1, Shahid Farooq Hospital Road, Rahman Plaza (second floor)',
                'ownership'            => 'Private',
                'activities'           => '2002',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],  

                [
                'name'                 => 'Mahona Pharmacies.',
                'division_id' => '2',
                'district_id' => '14',
                'category_id' => '4',    
                'address'              => 'Babor Mahal Road ',
                'ownership'            => 'Private',
                'activities'           => '2005',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],
                [
                'name'                 => 'Aryan General Hospital and Diagnostic Centre.',
                'division_id' => '2',
                'district_id' => '15',
                'category_id' => '4',    
                'address'              => 'Khah 72, tetula floor ',
                'ownership'            => 'Private',
                'activities'           => '2009',
                'beds'                 =>'100',
                'doctors'              =>'600',
                'phone'             => '9860989556',
                ],
                [
                'name'                 => 'Victoria Health Care Ltd.',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '5',    
                'address'              => ' Cosmopolitan Center (second floor), 222, Babar Road, Mohammadpur, Dhaka 1207',
                'ownership'            => 'Private',
                'activities'           => '2008',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],  
                [
                'name'                 => 'Sonargaon Medical Center.',
                'division_id' => '1',
                'district_id' => '2',
                'category_id' => '5',    
                'address'              => '421, Tipu Sultan Road ',
                'ownership'            => 'Private',
                'activities'           => '2008',
                'beds'                 =>'130',
                'doctors'              =>'50',
                'phone'             => '986489556',
                ],
                [
                'name'                 => 'SK Hospital.',
                'division_id' => '2',
                'district_id' => '14',
                'category_id' => '5',    
                'address'              => 'X / K, Pius cottage Housing Society, Ring Road ',
                'ownership'            => 'Local funding',
                'activities'           => '1999',
                'beds'                 =>'90',
                'doctors'              =>'30',
                'phone'             => '986489556',
                ],  
                [
                'name'                 => 'Mirpur Delta Health Care Ltd.',
                'division_id' => '1',
                'district_id' => '1',
                'category_id' => '1',    
                'address'              => 'mirpur 11 , -45 platah next to the mosque , sekasanah 7, 1216 pallabi dhaka 1216',
                'ownership'            => 'Private',
                'activities'           => '2014',
                'beds'                 =>'100',
                'doctors'              =>'30',
                'phone'             => '9857556',
                ]
        
            ]);
    }
}
